#!/bin/bash
#SBATCH -N 1
#SBATCH -n 8
#SBATCH --gres=gpu:1
#SBATCH --time=10:00:00 
export THEANO_FLAGS='device=cuda'
while true; do
    miniramp train --problem=miniramp.problems.cifar10 --sampler=deepgrammar.samplers.random --save
done
